# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Distribute app via diawi"
  lane :beta do
    sh("yarn") 
    gradle(task: "clean assembleRelease")
    diawi(
      token: "2SZhLzXlmDDLV5eKishHC6lXcJj7FuUxSMUY2SQrvn"
    )
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

end
